package com.achintha.orderservice.exception;

/** Stable, machine-readable error codes returned in {@link ApiError#code()}. Never rename a published code. */
public enum ErrorCode {
    // Generic
    VALIDATION_FAILED,
    MALFORMED_REQUEST,
    BAD_REQUEST,
    INVALID_SORT,
    NOT_FOUND,
    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE,
    CONCURRENT_MODIFICATION,
    INTERNAL_ERROR,
    SERVICE_UNAVAILABLE,

    // Authentication and authorization
    UNAUTHORIZED,
    ACCESS_DENIED,
    TOKEN_REVOKED,

    // Idempotency
    IDEMPOTENCY_KEY_REQUIRED,
    IDEMPOTENCY_KEY_REUSED,
    IDEMPOTENCY_REQUEST_IN_PROGRESS,

    // Cart
    CART_ITEM_NOT_FOUND,
    CART_FULL,
    VARIANT_NOT_AVAILABLE,
    INSUFFICIENT_STOCK,

    // Checkout preconditions (section 6.1), one code each
    CUSTOMER_BANNED,
    CUSTOMER_NOT_ACTIVE,
    STORE_NOT_ACCEPTING_ORDERS,
    CUSTOMER_BLOCKED_BY_STORE,
    COD_NOT_AVAILABLE_FOR_STORE,
    COD_NOT_ALLOWED_FOR_PRODUCT,
    COD_SUSPENDED,
    OPEN_ORDER_LIMIT_REACHED,
    ADDRESS_NOT_FOUND,
    PAYMENT_METHOD_MISSING,
    CHECKOUT_FAILED,

    // Orders and the state machine
    INVALID_ORDER_STATE,
    ACTION_NOT_PERMITTED,
    QUOTE_REVISION_LIMIT_REACHED,
    INVALID_QUOTE,
    COURIER_NOT_AVAILABLE,
    INVALID_TRACKING_NUMBER,
    DEADLINE_PASSED,

    // Payments
    PAYMENT_REJECTED,
    BANK_ACCOUNT_NOT_AVAILABLE,

    // COD objections, complaints, blocks
    OBJECTION_NOT_ALLOWED,
    OBJECTION_ALREADY_EXISTS,
    OBJECTION_ALREADY_DECIDED,
    COMPLAINT_NOT_ALLOWED,
    COMPLAINT_ALREADY_RESPONDED,
    COMPLAINT_ALREADY_DECIDED,
    CUSTOMER_ALREADY_BLOCKED,
    FLAG_ALREADY_REVIEWED
}
